### ISSUE TITLE
[docs] doc for docker caido is not up-to-date.

### ISSUE THREAD

**Issue by cocoonkid** [caido/caido#639]
the correct command is:

docker run --rm -p 7000:8080 \
  -v /home/my_user/my_data:/home/caido/.local/share/caido caido/caido:latest

here is a docker compose that can be added as well.

```
services:
    caido:
        image: 'caido/caido:latest'
        restart: unless-stopped
        ports:
            - '7000:8080'
        volumes:
            - ' /home/my_user/my_data:/home/caido/.local/share/caido'

```
I also suggest allow changing /home/caido/.local/share/caido to something else via env var.

Testing this out now. Liking it so far. Keep up the great work.
